columbusrb/columbusrb.com

app/views/layouts/application.html.slim

Fixes columbusrb/columbusrb.com#16.

Add a GitHub link to the page.

---

public/companies.yml

This is the start of a document listing companies around Columbus that use Ruby.
Inspired by http://vanruby.org/companies.html.

Beginning a company list

---

Dockerfile
README.md
bin/start
config/database.yml
docker-compose.yml
script/docker-run
script/docker-start

* "Works on my machine"
* The scripts are a convenience for those not familiar with docker, I would not call them "tried and true" but they seem to do what is intended.

Docker updates

---

app/views/pages/now.html.slim

Testing out configuration of continuous deployment after merging to master #22 and correct the link from the old repo to github.

updated the open source link

---

app/assets/stylesheets/application.css.scss.erb
app/controllers/pages_controller.rb
app/views/pages/now.html.slim

Paired with Nick Collins to add the Board of Directors to the main page of the CRB site.
Closes #12.

Adding board of directors

---

app/views/layouts/application.html.slim

Just a link change. Probably didn't need to create a PR for this :D

changed mailing list to new link

---

app/models/meeting.rb

Made it so that you can generate a bunch of new meetings without erasing them all.

generate meetings for the future

---

public/companies.yml

Add Root Insurance

---

app/controllers/pages_controller.rb
app/models/meeting.rb

In relation to this issue https://github.com/columbusrb/columbusrb.com/issues/39
Updated to remove the method that populates 72 months in advance and replaced with a method that first checks to make sure the next date is not set or sets the date if necessary. 
Tested by removing all the dates and called the new method. Tested to ensure that it correctly determines which month to schedule the next meeting.

Gh time bomb

---

app/views/pages/now.html.slim

This is a pull request to resolve issue #38 by giving more detailed parking information

Updated Parking Information

---

app/views/pages/now.html.slim

Make the company name link to their website Issue #49

---

public/companies.yml

Would love to add our company to your list of companies that use ruby.

Add Switchbox Inc as a Company.

---

public/companies.yml

Adds Bold Penguin

---

app/controllers/speakers_controller.rb
app/views/speakers/index.html.erb

Moved the speaker link to the top of the page and reordered the speaker page to list from newest to oldest.

moved add speaker link and changed display order

---

public/companies.yml

We're new in town, so just getting us on the list!

Add Upstart to company list

---

config/initializers/assets.rb

We have to explicitly precompile stylesheets now.

---

public/companies.yml

Adds 'Your Lighting Brand' to the list of Ruby using companies. Thanks!

Add your lighting brand as company that uses ruby

---

Gemfile
Gemfile.lock
app/controllers/pages_controller.rb
app/models/meetup_group.rb
app/models/member.rb
app/views/layouts/application.html.slim
config/environments/development.rb
config/environments/production.rb
db/seeds.rb

Wanted to add the meetup.com API to show up to date total members count for CRB. Sorry about the last pull request.

Meetup api

---

public/companies.yml

A small bootstrapped company that we think is getting pretty interesting
https://pigeonforteachers.com

Add Pigeon to Companies list

---

public/companies.yml

Add ticketfire to company list

---

.gitignore
app/controllers/pages_controller.rb
app/views/layouts/application.html.slim
app/views/pages/location.html.slim
config/routes.rb

An announcement needs to be made.

An announcement.

---

public/companies.yml

We're a remote team with a 1 co-founder and an early employee based in Columbus. Would love to join our friends @ Beam on this list!

add Sana to companies.yml

---

contributing.md

Urges contributors to join our Slack Organization twice and identifies two common (for me) errors and their solutions!

Adds slightly more documentation around contributing

---

app/views/pages/now.html.slim

We are in person tonight! This PR just changes our location! No I didn't view it because I'm at work and didn't have time to mess with the setup scripts not working.

Update location of Tonight's Meeting
